services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.6-alpine
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

volumes:
  db-data: