ktor:
  application:
    modules:
      - cl.sixtape.ApplicationKt.module
  deployment:
      port: "$KTOR_PORT:8080"
  development: $KTOR_DEV_MODE
db:
  jdbcURL: $KTOR_DB_URL
  driver: $KTOR_DB_DRIVER
  user: $DB_USER
  password: $DB_PASSWORD